import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ClipboardCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { FeedbackAlert } from "@/components/feedback-alert";
import { ReservationRulesNotice } from "@/components/reservations/reservation-rules-notice";
import { ReservationSummary, formatUtc } from "@/components/reservations/reservation-summary";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";

export function CreateReservationPage() {
  const { session } = useAuth(); const navigate = useNavigate();
  const [prosumers, setProsumers] = useState([]); const [nodes, setNodes] = useState([]); const [slots, setSlots] = useState([]);
  const [prosumerNic, setProsumerNic] = useState(""); const [nodeId, setNodeId] = useState(""); const [slotId, setSlotId] = useState(""); const [energyAmountKw, setEnergy] = useState("");
  const [reviewing, setReviewing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.getProsumers(session.token, "Active"), api.getNodes(session.token)]).then(([p, n]) => { setProsumers(p); setNodes(n); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [session.token]);
  useEffect(() => { setSlotId(""); setSlots([]); if (!nodeId) return; api.getBookingSlotsByNode(session.token, nodeId).then(data => { const now = Date.now(), max = now + 7 * 86400000; setSlots(data.filter(x => x.isActive && x.status === "Available" && new Date(x.startTime).getTime() > now && new Date(x.startTime).getTime() <= max)); }).catch(e => setError(e.message)); }, [nodeId, session.token]);
  const prosumer = useMemo(() => prosumers.find(x => x.id === prosumerNic), [prosumers, prosumerNic]); const node = useMemo(() => nodes.find(x => x.id === nodeId), [nodes, nodeId]); const slot = useMemo(() => slots.find(x => x.id === slotId), [slots, slotId]);
  const valid = prosumer && node && slot && Number(energyAmountKw) > 0 && Number(energyAmountKw) <= Number(slot.capacityKw);
  async function create() { setSaving(true); setError(""); try { const result = await api.createReservation(session.token, { prosumerNic, nodeId, slotId, energyAmountKw: Number(energyAmountKw) }); navigate(`/reservations/${result.id}/summary`, { state: { operation: "created" } }); } catch (e) { setError(e.message); setReviewing(false); } finally { setSaving(false); } }
  return <section className="space-y-5"><div><p className="text-sm font-semibold text-brand-600">Reservations / Create</p><h1 className="text-2xl font-bold text-slate-900">Create reservation</h1><p className="text-sm text-slate-500">Create an energy booking for an existing active Prosumer.</p></div>{error && <FeedbackAlert>{error}</FeedbackAlert>}<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle>{reviewing ? "Review reservation" : "Reservation information"}</CardTitle></CardHeader><CardContent className="space-y-4">{loading ? <p>Loading active Prosumers and stations...</p> : <><Field label="Prosumer (NIC or name)"><Select value={prosumerNic} onValueChange={v => { setProsumerNic(v); setReviewing(false); }} disabled={reviewing}><SelectTrigger><SelectValue placeholder="Select an active Prosumer" /></SelectTrigger><SelectContent>{prosumers.map(p => <SelectItem key={p.id} value={p.id}>{p.fullName} — {p.id} ({p.accountStatus})</SelectItem>)}</SelectContent></Select></Field><Field label="Microgrid node"><Select value={nodeId} onValueChange={v => { setNodeId(v); setReviewing(false); }} disabled={reviewing}><SelectTrigger><SelectValue placeholder="Select a station" /></SelectTrigger><SelectContent>{nodes.map(n => <SelectItem key={n.id} value={n.id}>{n.name} — {n.capacityKw} kW</SelectItem>)}</SelectContent></Select></Field><Field label="Available booking slot"><Select value={slotId} onValueChange={v => { setSlotId(v); setReviewing(false); }} disabled={!nodeId || reviewing}><SelectTrigger><SelectValue placeholder={nodeId ? "Select an available slot" : "Select a station first"} /></SelectTrigger><SelectContent>{slots.map(s => <SelectItem key={s.id} value={s.id}>{formatUtc(s.startTime)} – {formatUtc(s.endTime)} ({s.capacityKw} kW)</SelectItem>)}</SelectContent></Select>{nodeId && slots.length === 0 && <p className="mt-1 text-xs text-amber-700">No available slots within the next seven days.</p>}</Field><Field label="Energy amount (kWh)"><Input type="number" min="0.01" step="0.01" max={slot?.capacityKw} value={energyAmountKw} onChange={e => { setEnergy(e.target.value); setReviewing(false); }} disabled={reviewing} /></Field><ReservationRulesNotice /></>}</CardContent></Card><div className="space-y-4"><ReservationSummary prosumer={prosumer} node={node} slot={slot} energyAmount={energyAmountKw} />{reviewing && <FeedbackAlert variant="success">Review the information, then create the reservation. Its initial status will be Pending.</FeedbackAlert>}</div></div><div className="flex justify-end gap-3"><Button variant="outline" onClick={() => reviewing ? setReviewing(false) : navigate("/reservations")}><ArrowLeft size={16} />{reviewing ? "Back to edit" : "Cancel"}</Button>{reviewing ? <Button onClick={create} disabled={saving}><Check size={16} />{saving ? "Creating..." : "Create reservation"}</Button> : <Button onClick={() => setReviewing(true)} disabled={!valid}><ClipboardCheck size={16} />Review reservation</Button>}</div></section>;
}
function Field({ label, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
